name: nikon_field_monitor
description: "NikonFieldMonitor - Professional wireless/USB live view monitor & remote controller for Nikon Z-series and PTP/IP cameras."
publish_to: "none"
version: 1.0.6+6
license: MIT

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.1
  wakelock_plus: ^1.1.6
  path_provider: ^2.1.4
  file_picker: ^6.2.1
  collection: ^1.18.0
  uuid: ^4.4.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  package_info_plus: ^8.0.0
  package_info_plus_platform_interface: ^3.0.0
  wakelock_plus: 1.1.6
  wakelock_plus_platform_interface: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/shaders/
    - assets/luts/
    - android/app/src/main/assets/shaders/
    - android/app/src/main/assets/luts/
